name: banking_mobile_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  #firebase
  firebase_core: ^2.20.0
  firebase_auth: ^4.12.0
  cloud_firestore: ^4.12.1

  # state management
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2

  #equatable
  equatable: ^2.0.5

  #route
  auto_route: ^7.8.2

  ## image
  flutter_svg: ^2.0.8
  flutter_gen: ^5.3.2

  # localizations
  intl: ^0.18.1
  flutter_localizations:
    sdk: flutter
  freezed: ^2.4.5
  freezed_annotation: ^2.4.1
  flavor: ^2.0.0
  flutter_iban_scanner: ^0.1.1
  camera: ^0.8.1+7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.2
  auto_route_generator: ^7.3.2
  json_serializable: ^6.7.1

  ## code analysis
  very_good_analysis: ^5.1.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
